### ISSUE TITLE
Glitchy writing at the end of the note

### ISSUE THREAD

**Issue by pawel-ilnicki** [jensmtg/influx#8]
When you write quickly at the very end of the note, near the influx footnote, the words sometimes slip downwards, below the influx footnote. Couple miliseconds later they come back, but I lose my train of thought because of this.

**Comment by jensmtg** [comment]
Does it drop below the entire influx component or does it bleed into it?

**Comment by DeutscheGabanna** [comment]
my theme is minimal, if that makes any difference

**Comment by jensmtg** [comment]
Fixed in latest version

**Comment by DeutscheGabanna** [comment]
Still occurs after updating to 1.1.1 for notes where influx is not visible.

**Comment by jensmtg** [comment]
Can you provide a video? I'm unable to reproduce this issue.

**Comment by DeutscheGabanna** [comment]
https://user-images.githubusercontent.com/59067099/191283198-eef9735f-52d9-4fe0-b43e-2809d43b337c.mp4

**Comment by jensmtg** [comment]
Interesting. I'm not able to reproduce this on either mac or windows.
Do you get the same behaviour if you disable othe plugins?

The is a likely a bug in either codemirror or the registration of extensions for codemirror. It's not guaranteed it's in my power to fix this, but I'll have a look.

It may help to make some whitespaces before the influx component? (Press enter a time or two above thf influx-component, and then go up to the place you're writing)
