### ISSUE TITLE
Doesn't show up on some pages

### ISSUE THREAD

**Issue by sawft99** [jensmtg/influx#81]
**Describe the bug**
I have pages where the information doesn't show up anywhere on the bottom.

**To Reproduce**
I am not sure how to reproduce. It just seems to be an issue in my vault
I do have every thing to be included by default

**Expected behavior**
All pages to have influx information

**Screenshots**
The last line of my page where Influx should start to display but doesn't

![SS1](https://user-images.githubusercontent.com/81699231/234046918-a777e33b-1f0e-44fd-bed5-cb9a70f0972d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 2.1.2

**Additional context**
[The page](https://github.com/sawft99/Obsidian-SecPlus/blob/main/Sec%2B/Chapter%202%20-%20Malware/Malware.md) that is within my problem vault.

**Comment by maelstr08** [comment]
Same here, back links only show in Live Preview and only shows in some pages.

**Comment by cakechaser** [comment]
For me it's not showing anything on the pages with a header embedded on another page with ![[...]]
Could be the same thing in your vault.

For example in the scenario below it won't show any backlinks on Page 1 in Live Preview.

Page 1:
## Header
info

Page 2:
![[Page 1#Header]]

**Comment by LaikeSF** [comment]
I am having similar issues, but I do not have any backlinks in a header. With the new update to Obsidian to prevent memory leaks, the following error is now being thrown

`p.js:1 Error: Plugin "influx" is not passing Component in renderMarkdown. This is needed to avoid memory leaks when embedded contents register global event handlers.
    at t.render (app.js:1:1255232)
    at t.renderMarkdown (app.js:1:1255013)
    at ApiAdapter.eval (plugin:influx:23434:47)
    at Generator.next (<anonymous>)
    at eval (plugin:influx:66:61)
    at new Promise (<anonymous>)
    at __async (plugin:influx:50:10)
    at ApiAdapter.renderMarkdown (plugin:influx:23432:12)
    at ApiAdapter.eval (plugin:influx:23492:38)
    at Generator.next (<anonymous>)
t.render @ app.js:1
plugin:influx:23281 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at InlinkingFile.eval (plugin:influx:23281:37)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:influx:53:24)`

**Comment by sawft99** [comment]
Another issue I notice. If I have page A and page B. Page A starts with a ! in the title. It links to page B and Influx completely disappears from the bottom portion of page B. Even after I remove the ! from the title it takes awhile to come back.

I think linking from a table also breaks it. If i have a table, vocabulary for example, and I link back to the original document where the definition came from, the original document loses the influx portion at the botto. If I cut everything in the vocab document the text returns in the original document. If i make a link in the vocab document such as [[originaldoc]] the full influx info will appear again in the original doc. If i then delete the [[originaldoc]] link in my vocab doc and then repaste my table back in, the influx info does not update on the original document and even shows the referenced link that no longer exists.

**Comment by ivan-lednev** [comment]
The plugin's been abandoned. Check out an alternative implementation: https://github.com/ivan-lednev/better-search-views

**Comment by semanticdata** [comment]
@merrkry I implemented a custom Markdown Processor following Obsidian documentation to display and handle reading mode for Influx. This hopefully addresses this issue. I have noticed that sometimes you have to scroll up/down to make it appear. Let me know if you are able to test this again.

**Comment by merrkry** [comment]
@semanticdata thanks for following up, but unfortunately the issue still exists:

- Influx might not show up in reading mode or at all in some pages. But again I didn't find a way to reliably reproduce.
- Influx sometimes pop into the middle of the content instead of stay at bottom in live preview mode.
- Influx is displayed as part of embedded file's (`![[]]`) content.

**Comment by semanticdata** [comment]
Thank you. I'll look into it some more when I have a chance.

**Comment by rudironsoni** [comment]
I fixed it the issue https://github.com/jensmtg/influx/issues/113, it is on a feature branch, you can install through BRAT: https://github.com/rudironsoni/influx/tree/feature/fix-table-cell-backlinks

PR to this repo's master: https://github.com/jensmtg/influx/pull/116
