### ISSUE TITLE
Process links in front matter properties and make this configurable

### ISSUE THREAD

**Issue by inettom** [jensmtg/influx#86]
*Please consider sponsoring the project when submitting feature requests.* - I did :-)

**Is your feature request related to a problem? Please describe.**
This is not a problem yet it would be great if also links in front matter properties are processed in the influx. Many plugins keep obsidian links in the FM properties and those are not referenced.

**Describe the solution you'd like**
Have obsidian links from front matter properties processed by influx. I would also consider adding this as a configurable option, i.e.
-  "Include links from front matter properties": yes/no, and 
-  "Property list (include links from all front matter properties if blank)": (comma separated list of front matter properties).  

**Describe alternatives you've considered**
a) Move all links to the content body (or b)duplicate them).  Neither solution works. For a) it breaks the other plugin behaviour for b) it is too much overhead and cumbersome to keep in sync.
 
**Additional context**
N/A

Many thanks!
Tom

**Comment by semanticdata** [comment]
This feature was just shipped was Influx 2.3.0. Please take a test drive it and let me know what you think!

**Comment by websurfer93** [comment]
I immediately took it for a test drive. I can see the new toggle button in the setting, but unfortunately, it does not seem to be working as expected on my end.

The empty boxes representing links from Frontmatter/Metadata are still visible in the list. It seems the filter is not successfully removing those entries from the view.

<img width="795" height="541" alt="Image" src="https://github.com/user-attachments/assets/3ef46280-f91f-4f4b-9d0b-fb93f0ca4319" />

**Comment by semanticdata** [comment]
> I immediately took it for a test drive. I can see the new toggle button in the setting, but unfortunately, it does not seem to be working as expected on my end.
> 
> The empty boxes representing links from Frontmatter/Metadata are still visible in the list. It seems the filter is not successfully removing those entries from the view.

@websurfer93 It looks like a cache validation bug. I'll work on it. Thank you for bringing it up!

**Comment by semanticdata** [comment]
Hopefully this is fixed in 2.3.1 now. I added new tests to try and catch this sort of regression in the future. Thank you.

**Comment by websurfer93** [comment]
Thanks for the update and the new tests.

However, I regret to report that the issue persists on my end even with v2.3.1. I updated the plugin and reloaded, but the empty boxes for frontmatter links are still rendering exactly as before.

I have attached a screenshot taken just now using v2.3.1 for your reference.

<img width="786" height="241" alt="Image" src="https://github.com/user-attachments/assets/1ce11875-9520-43bd-868d-a803afc26a23" />

**Comment by semanticdata** [comment]
Gotcha. This warrants a deeper investigation. Hopefully I'll have some time this weekend.

Thank you for checking and helping verify this bug. :)

**Comment by semanticdata** [comment]
This is being reworked in the next version. It includes a new data pipeline that properly separates links from the front matter and links from the note body. We implement better filtering and are using a new experimental search feature.

I am currently ironing out some kinks and performance concerns with typing updates. Once it's ready for release, the new version 3.0.0 should include these updates.
